services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
    ports:
      - 3306:3306