apiVersion: apps/v1
kind: Deployment
metadata:
  name: bystrof-isis5-dep
  labels:
    app: isis5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: isis5
  template:
    metadata:
      labels:
        app: isis5
    spec:
      containers:
        - name: isis5
          image: bystrof/isis5
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 64Mi
              cpu: 20m
            limits:
              memory: 128Mi
              cpu: 40m
          livenessProbe:
            httpGet:
              path: '/'
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 5