apiVersion: apps/v1
kind: Deployment
metadata:
  name: bystrof-isis4-dep
  labels:
    app: isis4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: isis4
  template:
    metadata:
      labels:
        app: isis4
    spec:
      containers:
        - name: isis4
          image: bystrof/isis4
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 64Mi
              cpu: 20m
            limits:
              memory: 128Mi
              cpu: 40m
          livenessProbe:
            httpGet:
              path: '/'
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 5